services:
  grafana-export-to-pdf:
    build: .
    ports:
      - "${EXPORT_SERVER_PORT:-3001}:${EXPORT_SERVER_PORT:-3001}"
    volumes:
      - ./output:/usr/src/app/output
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - EXPORT_SERVER_PORT=${EXPORT_SERVER_PORT:-3001}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - EXPAND_COLLAPSED_PANELS=${EXPAND_COLLAPSED_PANELS:-true}
      - PANEL_RENDER_TIMEOUT=${PANEL_RENDER_TIMEOUT:-8000}
      - PUPPETEER_NAVIGATION_TIMEOUT=${PUPPETEER_NAVIGATION_TIMEOUT:-120000}
      - PDF_WIDTH_PX=${PDF_WIDTH_PX:-1200}
      - FORCE_KIOSK_MODE=${FORCE_KIOSK_MODE:-false}
      - EXTRACT_DATE_AND_DASHBOARD_NAME_FROM_HTML_PANEL_ELEMENTS=${EXTRACT_DATE_AND_DASHBOARD_NAME_FROM_HTML_PANEL_ELEMENTS:-false}
